cloud:
  aws:
    credentials:
      access-key: ENC(WPdwElgvL4Cjj0ODh7Nmm2qG1MA1ypp5W7LrmIQre3c=)
      secret-key: ENC(wbKQxVj4md0jFy3CFmAwgPmptlvrxSF4jTX6RZCNPVJgn/tTDcUR3NA0LCm7nEGbTs1D0NfQlKE=)
    region:
      static: ap-northeast-2 #아시아 태평양 (서울)
    s3:
      bucket: ENC(YlTl06Wf2TgO8B6VnfJEnPmb6+38mevo)
    stack:
      auto: false


request:
  main:
    url: ENC(86/xgvQYGP5zlxnLAmfAhD0AMldEWX8b/QmR7E5AyazumVadjLZ2ACyftHyZ1fBi) // k
#    url: ENC(HL8nc4lTdwrlZ3Acmsvs7891nkCtFUNNEDAzxK229JeAXBX4HWewtQ==) cobby
#    url: http://localhost:15030/api/main